spring:
  application:
    name: todo-list
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: myuser
    url: jdbc:mysql://localhost:3306/todolist
    password: secret
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migrations/mysql
    schemas: todolist
    url: jdbc:mysql://localhost:3306/todolist
    password: secret
    user: myuser
management:
  endpoint:
    env:
      show-values: always